"""add insurance vitals medication_logs

Revision ID: 3b8812e012de
Revises: 414bd36d3994
Create Date: 2026-03-19 15:27:10.752317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b8812e012de'
down_revision: Union[str, Sequence[str], None] = '414bd36d3994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_details',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('patient_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('insurance_company', sa.String(length=255), nullable=False),
    sa.Column('policy_number', sa.String(length=255), nullable=False),
    sa.Column('hospital_name', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('medication_logs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('patient_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('patient_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vitals')
    op.drop_table('medication_logs')
    op.drop_table('insurance_details')
    # ### end Alembic commands ###
